name: Lint code samples

on:
  pull_request:
    branches: [master]

jobs:
  calculate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"sample_path\":$(echo [$(ls -d code/*/ | xargs printf '\"%s\",'  | tr -d ' ')])}"
  clippy:
    needs: calculate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.calculate-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install libudev-dev libasound2-dev
      - run: rustup component add clippy
      - name: Lint ${{ matrix.sample_path }}
        run: cd ${{ matrix.sample_path }} && cargo clippy -A clippy::type-complexity
